#' Plot model and data from \code{tidydrc()}
#'
#' A \code{ggplot} wrapper function for plotting the dose-response model fit and the data from the list-column output of \code{tidydrc()}
#'
#' @author Angel Angelov
#'
#' @param modeldf A list-column dataframe, generated by \code{tidydrc()}
#' @param ed50 Logical, whether to draw a line indicating the ED50 (effective dose for 50\% response).
#' @param confint Logical, whether to draw confidence bands around the fitted regression curve as a \code{geom_ribbon}
#' @param ... Arguments passed on to \code{aes()} of ggplot, as in \code{ggplot(aes(...))}
#'
#' @usage tidydrc_plot(modeldf, ed50 = FALSE, confint = FALSE, ...)
#'
#' @examples
#' # directly piping the output of tidydrc()
#' library(tidyverse)
#' p <- tidydrc_model(S.alba, Dose, DryMatter, model = LL.4(), Herbicide) %>%
#'      tidydrc_plot(ed50 = TRUE, confint = TRUE, color = ~Herbicide)
#' p
#'
#' # the ggplot object can be manipulated further as usual
#' p + facet_wrap(~Herbicide, ncol = 1) +
#'     scale_x_log10() +
#'     labs(title = "Potency of glyphosate and bentazone in Sinapsis alba")
#'
#' @export

tidydrc_plot <- function(modeldf, ed50 = FALSE, confint = FALSE, ...) {


  p <- modeldf %>% unnest(data) %>%
    ggplot(aes_(...)) +
    geom_point(aes_(~d,  ~r), alpha = 0.6, stroke = 0, size = 2) +
    geom_line(aes_(~dose, ~pred), data = modeldf %>% unnest(pred)) +
    theme_bw()
  ifelse(ed50 == FALSE,
         p,
         p <- p + geom_vline(aes_(xintercept = ~`e:(Intercept)`, ...),
                             linetype = 5,
                             data = modeldf %>% unnest(coefs) %>% spread(parameter, value))
  )
  ifelse(confint == FALSE,
         p,
         p <- p + geom_ribbon(aes_(x = ~dose, ymin = ~Lower, ymax = ~Upper, ...),
                              alpha = 0.2,
                              size = 0,
                              data = modeldf %>% unnest(pred)))

  return(p)

}
